//TODO: wyczyścić bazę danych z testowych użytkowników i dostosować ten plik do szybkiego testowania
@port = 5014
@name = szymon
@password = szymon
# Just user register
post http://localhost:{{port}}/auth/register
Content-Type: application/json

{
    "email": "{{name}}@gmail.com",
    "password":"{{password}}"
}

###
# ERROR CALL - User with that email already exit
post http://localhost:{{port}}/auth/register
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password":"admin"
}

# LOGIN ===================================

###
# Just user login
post http://localhost:{{port}}/auth/login
Content-Type: application/json

{
    "email": "{{name}}@gmail.com",
    "password":"{{password}}"
}

###
# ERROR CALL - User with that email doesn't exist
post http://localhost:{{port}}/auth/login
Content-Type: application/json

{
    "email": "gasdawfbegavaa@gmail.com",
    "password":"{{password}}"
}

###
# ERROR CALL - Wrong password
post http://localhost:{{port}}/auth/login
Content-Type: application/json

{
    "email": "{{name}}@gmail.com",
    "password":"ladawposvadwdasdawdawdne"
}

